GET http://localhost:8080/api/v1/company/ucu.edu.ua

###
GET http://localhost:8080/api/v1/company/elex.com

###
GET http://localhost:8080/api/v1/company/softserveinc.com

###
GET http://localhost:8080/api/v1/company

###
GET http://localhost:8080/api/v1/company/edx.org
