GET http://localhost:8080/api/v1/company/ucu.edu.ua

###
GET http://localhost:8080/api/v1/company/elex.com

###
GET http://localhost:8080/api/v1/company/softserve.com

###
GET http://localhost:8080/api/v1/company

###
GET http://localhost:8080/api/v1/company/edx.org

###
POST http://localhost:8080/api/v1/company
Content-Type: application/json

{
  "domain": "ucu.edu.ua",
  "name": "Ukrainian Catholic University",
  "employees": 12345
}

###
POST http://localhost:8080/api/v1/company
Content-Type: application/json

{
  "name": "softserve",
  "domain": "softserve.com"
}